export class Order {
  constructor(
    address_coordinates,
    address_string,
    address_string_2,
    category_name,
    delivery_note,
    orderID,
    os,
    product_name,
    recipient_email,
    recipient_name,
    recipient_phone_number,
    schedule,
    sender_email,
    sender_name,
    sender_phone_number,
    time_order_placed,
    zone,
    city
  ) {
    (this.address_coordinates = address_coordinates),
      (this.address_string = address_string),
      (this.address_string_2 = address_string_2),
      (this.category_name = category_name),
      (this.delivery_note = delivery_note),
      (this.orderID = orderID),
      (this.os = os),
      (this.product_name = product_name),
      (this.recipient_email = recipient_email),
      (this.recipient_name = recipient_name),
      (this.recipient_phone_number = recipient_phone_number),
      (this.schedule = schedule),
      (this.sender_email = sender_email),
      (this.sender_name = sender_name),
      (this.sender_phone_number = sender_phone_number),
      (this.time_order_placed = time_order_placed),
      (this.zone = zone),
      (this.city = city);
  }
}
